# Generated by Django 5.1.7 on 2025-05-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.supplies')),
            ],
        ),
    ]
